services:
  - type: web
    name: smartprintvit
    runtime: node
    plan: free
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: cd "student web app" && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
